name = "StatusSwitchingQP"
uuid = "73a7d86c-03e3-42fb-a0f5-70ef6cda08f4"
authors = ["Pharos Abad"]
version = "0.1.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
julia = "1"
PrecompileTools = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
